trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Python27
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
    displayName: 'Use Python 2.7'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'Test with Python 2.7'
